---
# tasks file for ansible-role-kvm

- name: include install repos
  ansible.builtin.include_tasks:
    install_repos.yml

- name: include configure users
  ansible.builtin.include_tasks:
    configure_users.yml

- name: copy authorized keys from github
  ansible.posix.authorized_key:
     user: jsorell
     state: present
     key: https://github.com/J-SirL.keys


- name: update OS
  ansible.builtin.dnf:
    name: "*"
    state: latest


## Install the programs required
- name: install packages {{ packages }}
  ansible.builtin.dnf:
    name: "{{ item }}"
  loop: "{{ packages }}"

- name: reload servcice
  ansible.builtin.systemd:
      daemon_reload: yes # not required. run daemon-reload before doing any other operations, to make sure systemd has read any changes.

- name: configure kvm
  ansible.builtin.include_tasks:
    configure_kvm.yml

- name: create new virt_pool
  ansible.builtin.include_tasks:
    create_virt_pool.yml
